spring.application.name=reorderkit
spring.datasource.url=jdbc:postgresql://localhost:5432/reorderkit
spring.datasource.username=bravemeow
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=validate