CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopify_shop_id VARCHAR(255) NOT NULL UNIQUE,
    shop_domain VARCHAR(255) NOT NULL UNIQUE,
    store_name VARCHAR(255) NOT NULL,
    access_token TEXT NOT NULL,
    merchant_email VARCHAR(320) NOT NULL,
    notification_email_override VARCHAR(320),
    default_lead_time_days INTEGER,
    default_buffer_days INTEGER,
    default_order_coverage_days INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_stores_default_lead_time_days
        CHECK (default_lead_time_days >= 0),
    CONSTRAINT chk_stores_default_buffer_days
        CHECK (default_buffer_days >= 0),
    CONSTRAINT chk_stores_default_order_coverage_days
        CHECK (default_order_coverage_days > 0)
);

CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    shopify_product_id VARCHAR(255) NOT NULL,
    shopify_variant_id VARCHAR(255) NOT NULL UNIQUE,
    product_title VARCHAR(255) NOT NULL,
    variant_title VARCHAR(255),
    sku VARCHAR(255),
    inventory_quantity INTEGER NOT NULL,
    on_order_quantity INTEGER NOT NULL DEFAULT 0,
    average_daily_sales_30d NUMERIC(12, 4) NOT NULL,
    lead_time_days_override INTEGER,
    buffer_days_override INTEGER,
    order_coverage_days_override INTEGER,
    last_synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_variants_store
        FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT chk_product_variants_inventory_quantity
        CHECK (inventory_quantity >= 0),
    CONSTRAINT chk_product_variants_on_order_quantity
        CHECK (on_order_quantity >= 0),
    CONSTRAINT chk_product_variants_average_daily_sales_30d
        CHECK (average_daily_sales_30d >= 0),
    CONSTRAINT chk_product_variants_lead_time_days_override
        CHECK (lead_time_days_override >= 0),
    CONSTRAINT chk_product_variants_buffer_days_override
        CHECK (buffer_days_override >= 0),
    CONSTRAINT chk_product_variants_order_coverage_days_override
        CHECK (order_coverage_days_override > 0)
);

CREATE TABLE reorder_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id BIGINT NOT NULL,
    inventory_quantity INTEGER NOT NULL,
    on_order_quantity INTEGER NOT NULL,
    average_daily_sales_30d NUMERIC(12, 4) NOT NULL,
    lead_time_days INTEGER NOT NULL,
    buffer_days INTEGER NOT NULL,
    order_coverage_days INTEGER NOT NULL,
    reorder_point INTEGER NOT NULL,
    target_inventory INTEGER NOT NULL,
    should_reorder BOOLEAN NOT NULL,
    recommended_quantity INTEGER NOT NULL,
    calculation_trigger VARCHAR(32) NOT NULL,
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reorder_history_product_variant
        FOREIGN KEY (product_variant_id) REFERENCES product_variants (id) ON DELETE CASCADE,
    CONSTRAINT chk_reorder_history_inventory_quantity
        CHECK (inventory_quantity >= 0),
    CONSTRAINT chk_reorder_history_on_order_quantity
        CHECK (on_order_quantity >= 0),
    CONSTRAINT chk_reorder_history_average_daily_sales_30d
        CHECK (average_daily_sales_30d > 0),
    CONSTRAINT chk_reorder_history_lead_time_days
        CHECK (lead_time_days >= 0),
    CONSTRAINT chk_reorder_history_buffer_days
        CHECK (buffer_days >= 0),
    CONSTRAINT chk_reorder_history_order_coverage_days
        CHECK (order_coverage_days > 0),
    CONSTRAINT chk_reorder_history_reorder_point
        CHECK (reorder_point >= 0),
    CONSTRAINT chk_reorder_history_target_inventory
        CHECK (target_inventory >= 0),
    CONSTRAINT chk_reorder_history_recommended_quantity
        CHECK (recommended_quantity >= 0),
    CONSTRAINT chk_reorder_history_calculation_trigger
        CHECK (calculation_trigger IN ('MANUAL_REFRESH', 'SCHEDULED'))
);

CREATE TABLE notification_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    notification_date DATE NOT NULL,
    recipient_email VARCHAR(320) NOT NULL,
    attempt_number INTEGER NOT NULL,
    successful BOOLEAN NOT NULL,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMPTZ,
    failure_message TEXT,

    CONSTRAINT fk_notification_history_store
        FOREIGN KEY (store_id) REFERENCES stores (id) ON DELETE CASCADE,
    CONSTRAINT uq_notification_history_daily_attempt
        UNIQUE (store_id, notification_date, attempt_number),
    CONSTRAINT chk_notification_history_attempt_number
        CHECK (attempt_number BETWEEN 1 AND 3),
    CONSTRAINT chk_notification_history_sent_at
        CHECK (
            (successful = TRUE AND sent_at IS NOT NULL)
            OR (successful = FALSE AND sent_at IS NULL)
        )
);
